/*
  This file is automatically generated. Any changes will be overwritten.
  Modify add-order.component.ts instead.
*/
import { Injector, OnInit, OnDestroy } from '@angular/core';
import { NavigationEnd, Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { Subscription } from 'rxjs';

import { TestService } from '../test.service';
import { SecurityService } from '../security.service';

/*
  Component properties set from design-time.
*/
const { components } = require('../../../../meta/pages/add-order.json');

export class AddOrderGenerated implements OnInit, OnDestroy {
  components = components;
  // Array of messages displayed by the notification component.
  messages = [];

  router: Router;

  route: ActivatedRoute;

  _location: Location;

  subscription: Subscription;

  security: SecurityService;

  test: TestService;

  parameters: any;

  Security: any;

  ngOnInit() {
    this.subscription = this.router.events.subscribe(event => {
      if (event instanceof NavigationEnd && this instanceof <any>this.route.component) {
        this.parameters = this.route.snapshot.params;

        this.load();
      }
    });
  }

  ngOnDestroy() {
    this.subscription.unsubscribe();
  }


  load() {

  }

  form0Cancel(event: any) {
    this._location.back();
  }

  form0Submit(event: any) {
    this.test.createOrder(event)
    .then(result => {
      this.router.navigate([{ outlets: { popup: null } }]).then(() => this.router.navigate(['orders']));
    }, result => {
      this.messages.push({ severity: "error", summary: `Error`, detail: `Unable to create new Order!` });
    });
  }

  constructor(injector: Injector) {
    this.router = injector.get(Router);

    this._location = injector.get(Location);

    this.route = injector.get(ActivatedRoute);

    this.test = injector.get(TestService);
    this.security = injector.get(SecurityService);
  }
}
